# Generated by Django 4.2.2 on 2023-06-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="buyer", name="email",),
    ]
